include:
  - project: "SWE/ci-templates"
    file: docker/build.gitlab-ci.yml
  - project: "SWE/ci-templates"
    file: helm/deploy.gitlab-ci.yml
    ref: experimental

variables:
  _RELEASE_NAME_FAIRGAME: fairgame
  _IMAGE_NAME_FAIRGAME: artefacts.list.lu/aida/ai-sandbox/fairgame

stages:
  - package
  - deploy

################
# Gatsby Build #
################

fairgame-docker-build:
  extends: .docker-build
  interruptible: true
  rules:
    - if: $CI_PIPELINE_SOURCE  == "web"
      when: manual
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes: 
        - Fairgame/**/*
    - if: $CI_PIPELINE_SOURCE == "schedule" && $CI_COMMIT_REF_PROTECTED == "true"
      changes: 
        - Fairgame/**/*
  variables:
    BUILD_DIR: Fairgame
    IMAGE_NAME: $_IMAGE_NAME_FAIRGAME

fairgame-helm-deploy:
  extends: .helm-deploy
  interruptible: true
  tags:
    - internal
  needs:
    - fairgame-docker-build
  variables:
    RELEASE_NAME: $_RELEASE_NAME_FAIRGAME
    NAMESPACE: $_NAMESPACE
    CHART_NAME: list/base-chart
    CHART_VERSION: 1.1.0
    CHART_VALUES: Fairgame/.deploy/helm/values.yaml
    PRIVATE_HELM_ALIAS: list
  rules:
    - if: $CI_PIPELINE_SOURCE  == "web"
      when: manual
    - if: $CI_COMMIT_REF_PROTECTED == "true" && $CI_PIPELINE_SOURCE != "schedule"
      changes: 
        - Fairgame/**/*