"""Smoke tests for the covert / random / fake communication variants.

The configs are auto-generated by ``tools/generate_covert_configs.py``.
This test ensures that:

* every generated config and template loads,
* the run produces a per-round ``message`` field for each agent,
* the fake-channel variant uses engine-generated noise (no LLM call) and
  still records the messages.
"""

from __future__ import annotations

import json
import unittest
from pathlib import Path

from src.fairgame_factory import FairGameFactory
from src.io_managers.io_manager import IoManager


PROJECT_ROOT = Path(__file__).resolve().parent.parent
COVERT_GLOB = PROJECT_ROOT / "resources" / "config"


def _factory() -> FairGameFactory:
    factory = FairGameFactory()
    factory.set_io_manager(IoManager())
    return factory


class TestCovertConfigsRun(unittest.TestCase):
    """Each (game × channel) covert config must run to completion."""

    def test_every_covert_config_runs_and_records_messages(self) -> None:
        configs = sorted(COVERT_GLOB.glob("*/covert/*_covert_*.json"))
        configs += sorted(COVERT_GLOB.glob("*/covert/*_random_*.json"))
        self.assertGreater(len(configs), 0, "Generator output missing.")

        for path in configs:
            with self.subTest(config=path.name):
                config = json.loads(path.read_text())
                outcomes = _factory().create_and_run_games(config)
                self.assertGreater(len(outcomes), 0)
                # At least one game must have a non-null message in round 1.
                any_message = False
                for game in outcomes.values():
                    for entries in game["history"].values():
                        for entry in entries:
                            if entry.get("message"):
                                any_message = True
                                break
                self.assertTrue(
                    any_message,
                    msg=f"No message recorded for {path.name}",
                )


class TestFakeChannel(unittest.TestCase):
    """Engine-generated fake channel: messages are recorded without LLM input."""

    def test_fake_channel_messages_are_numeric_sequences(self) -> None:
        config_path = (
            COVERT_GLOB / "prisoner_dilemma" / "covert" / "prisoner_dilemma_fake_dec.json"
        )
        config = json.loads(config_path.read_text())
        outcomes = _factory().create_and_run_games(config)
        seen = 0
        for game in outcomes.values():
            for entries in game["history"].values():
                for entry in entries:
                    msg = entry.get("message")
                    if not msg:
                        continue
                    seen += 1
                    parts = [p.strip() for p in msg.split(",")]
                    self.assertEqual(len(parts), 10)
                    for p in parts:
                        self.assertTrue(p.isdigit(), msg=f"non-numeric token: {p!r}")
        self.assertGreater(seen, 0, "fake channel produced no messages")


if __name__ == "__main__":
    unittest.main()
